name: build

on: [push]

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.1
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build
        run: |
          GOOS=linux go build -o ./bin/myhttp myhttp.go
          ./bin/myhttp -h
